# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QPixmap
from included import *
from lcgLemer import *
from simple_lcg import *
from static_function import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(616, 700)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 601, 670))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(80, 40, 431, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(80, 120, 160, 41))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(350, 120, 160, 41))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_3.addWidget(self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(240, 170, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.click_uniform)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 229, 554, 408))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(70, 10, 459, 71))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButton_4 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_4.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_4.addWidget(self.radioButton_5)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(70, 80, 459, 71))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.verticalLayoutWidget_5)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_5.addWidget(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(self.verticalLayoutWidget_5)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_5.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.verticalLayoutWidget_5)
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout_5.addWidget(self.radioButton_8)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(20, 250, 554, 408))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(80, 160, 160, 47))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_6.addWidget(self.lineEdit_3)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(350, 160, 160, 47))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_7.addWidget(self.lineEdit_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 210, 111, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.click_triangular)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(80, 170, 160, 47))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_8.addWidget(self.lineEdit_5)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(70, 90, 459, 71))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.radioButton_9 = QtWidgets.QRadioButton(self.verticalLayoutWidget_9)
        self.radioButton_9.setObjectName("radioButton_9")
        self.verticalLayout_9.addWidget(self.radioButton_9)
        self.radioButton_10 = QtWidgets.QRadioButton(self.verticalLayoutWidget_9)
        self.radioButton_10.setObjectName("radioButton_10")
        self.verticalLayout_9.addWidget(self.radioButton_10)
        self.radioButton_11 = QtWidgets.QRadioButton(self.verticalLayoutWidget_9)
        self.radioButton_11.setObjectName("radioButton_11")
        self.verticalLayout_9.addWidget(self.radioButton_11)
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(70, 20, 459, 71))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.radioButton_12 = QtWidgets.QRadioButton(self.verticalLayoutWidget_10)
        self.radioButton_12.setObjectName("radioButton_12")
        self.verticalLayout_10.addWidget(self.radioButton_12)
        self.radioButton_13 = QtWidgets.QRadioButton(self.verticalLayoutWidget_10)
        self.radioButton_13.setObjectName("radioButton_13")
        self.verticalLayout_10.addWidget(self.radioButton_13)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 220, 111, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.click_normal)
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(20, 310, 554, 408))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(350, 170, 160, 47))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_11.addWidget(self.label_9)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_11)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_11.addWidget(self.lineEdit_6)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(40, 160, 151, 47))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_12.addWidget(self.label_10)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.verticalLayoutWidget_12)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_12.addWidget(self.lineEdit_7)
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(70, 80, 459, 71))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.radioButton_14 = QtWidgets.QRadioButton(self.verticalLayoutWidget_13)
        self.radioButton_14.setObjectName("radioButton_14")
        self.verticalLayout_13.addWidget(self.radioButton_14)
        self.radioButton_15 = QtWidgets.QRadioButton(self.verticalLayoutWidget_13)
        self.radioButton_15.setObjectName("radioButton_15")
        self.verticalLayout_13.addWidget(self.radioButton_15)
        self.radioButton_16 = QtWidgets.QRadioButton(self.verticalLayoutWidget_13)
        self.radioButton_16.setObjectName("radioButton_16")
        self.verticalLayout_13.addWidget(self.radioButton_16)
        self.verticalLayoutWidget_14 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(70, 10, 459, 71))
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.radioButton_17 = QtWidgets.QRadioButton(self.verticalLayoutWidget_14)
        self.radioButton_17.setObjectName("radioButton_17")
        self.verticalLayout_14.addWidget(self.radioButton_17)
        self.radioButton_18 = QtWidgets.QRadioButton(self.verticalLayoutWidget_14)
        self.radioButton_18.setObjectName("radioButton_18")
        self.verticalLayout_14.addWidget(self.radioButton_18)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_4.setGeometry(QtCore.QRect(240, 210, 111, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(20, 300, 554, 408))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.verticalLayoutWidget_15 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(210, 160, 160, 47))
        self.verticalLayoutWidget_15.setObjectName("verticalLayoutWidget_15")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_15)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_15.addWidget(self.label_12)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.verticalLayoutWidget_15)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_15.addWidget(self.lineEdit_8)
        self.verticalLayoutWidget_16 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_16.setGeometry(QtCore.QRect(390, 160, 71, 47))
        self.verticalLayoutWidget_16.setObjectName("verticalLayoutWidget_16")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_16)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_16.addWidget(self.label_13)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.verticalLayoutWidget_16)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_16.addWidget(self.lineEdit_9)
        self.verticalLayoutWidget_17 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_17.setGeometry(QtCore.QRect(480, 160, 71, 47))
        self.verticalLayoutWidget_17.setObjectName("verticalLayoutWidget_17")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_17)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_17.addWidget(self.label_14)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.verticalLayoutWidget_17)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_17.addWidget(self.lineEdit_10)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayoutWidget_35 = QtWidgets.QWidget(self.tab_5)
        self.verticalLayoutWidget_35.setGeometry(QtCore.QRect(50, 90, 160, 47))
        self.verticalLayoutWidget_35.setObjectName("verticalLayoutWidget_35")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_35)
        self.verticalLayout_42.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.label_35 = QtWidgets.QLabel(self.verticalLayoutWidget_35)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_42.addWidget(self.label_35)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.verticalLayoutWidget_35)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.verticalLayout_42.addWidget(self.lineEdit_27)
        self.verticalLayoutWidget_36 = QtWidgets.QWidget(self.tab_5)
        self.verticalLayoutWidget_36.setGeometry(QtCore.QRect(220, 90, 160, 47))
        self.verticalLayoutWidget_36.setObjectName("verticalLayoutWidget_36")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_36)
        self.verticalLayout_43.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.label_36 = QtWidgets.QLabel(self.verticalLayoutWidget_36)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_43.addWidget(self.label_36)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.verticalLayoutWidget_36)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.verticalLayout_43.addWidget(self.lineEdit_28)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_9.setGeometry(QtCore.QRect(250, 141, 111, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayoutWidget_37 = QtWidgets.QWidget(self.tab_5)
        self.verticalLayoutWidget_37.setGeometry(QtCore.QRect(90, 11, 459, 71))
        self.verticalLayoutWidget_37.setObjectName("verticalLayoutWidget_37")
        self.verticalLayout_44 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_37)
        self.verticalLayout_44.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.radioButton_40 = QtWidgets.QRadioButton(self.verticalLayoutWidget_37)
        self.radioButton_40.setObjectName("radioButton_40")
        self.verticalLayout_44.addWidget(self.radioButton_40)
        self.radioButton_41 = QtWidgets.QRadioButton(self.verticalLayoutWidget_37)
        self.radioButton_41.setObjectName("radioButton_41")
        self.verticalLayout_44.addWidget(self.radioButton_41)
        self.radioButton_42 = QtWidgets.QRadioButton(self.verticalLayoutWidget_37)
        self.radioButton_42.setObjectName("radioButton_42")
        self.verticalLayout_44.addWidget(self.radioButton_42)
        self.label_37 = QtWidgets.QLabel(self.tab_5)
        self.label_37.setGeometry(QtCore.QRect(20, 200, 554, 408))
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.verticalLayoutWidget_38 = QtWidgets.QWidget(self.tab_5)
        self.verticalLayoutWidget_38.setGeometry(QtCore.QRect(400, 90, 71, 47))
        self.verticalLayoutWidget_38.setObjectName("verticalLayoutWidget_38")
        self.verticalLayout_45 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_38)
        self.verticalLayout_45.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.label_38 = QtWidgets.QLabel(self.verticalLayoutWidget_38)
        self.label_38.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_45.addWidget(self.label_38)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.verticalLayoutWidget_38)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.verticalLayout_45.addWidget(self.lineEdit_29)
        self.verticalLayoutWidget_39 = QtWidgets.QWidget(self.tab_5)
        self.verticalLayoutWidget_39.setGeometry(QtCore.QRect(490, 90, 71, 47))
        self.verticalLayoutWidget_39.setObjectName("verticalLayoutWidget_39")
        self.verticalLayout_46 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_39)
        self.verticalLayout_46.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.label_39 = QtWidgets.QLabel(self.verticalLayoutWidget_39)
        self.label_39.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_46.addWidget(self.label_39)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.verticalLayoutWidget_39)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.verticalLayout_46.addWidget(self.lineEdit_30)
        self.tabWidget.addTab(self.tab_5, "")
        self.horizontalSlider = QtWidgets.QSlider(Dialog)
        self.horizontalSlider.setGeometry(QtCore.QRect(130, 820, 391, 22))
        self.horizontalSlider.setMaximum(200)
        self.horizontalSlider.setProperty("value", 100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def load_image(self, file_name, label_link, scale):
        pixmap = QPixmap(file_name)

        #self.label_3.setPixmap(pixmap.scaledToWidth(576))
        label_link.setPixmap(pixmap.scaledToWidth(scale))

    def click_uniform(self):
        dist_name = 'uniform'
        elements = int(self.lineEdit.text())
        intervals = int(self.lineEdit_2.text())
        result_array = [0 for i in range(intervals)]
        if self.radioButton.isChecked():
            gen_name = 'default'
            for i in range(elements):
                result_array[get_bin(get_rand(gen_name, dist_name, min=0, max=1), binscount=intervals)] += 1
            draw_fun(result_array, intervals, gen_title(gen_name, dist_name))
            self.load_image('мой график.png', self.label_3, 560)
        elif self.radioButton_2.isChecked():
            gen_name = 'simple'
            for i in range(elements):
                result_array[get_bin(get_rand(gen_name, dist_name, min=0, max=1), binscount=intervals)] += 1
            draw_fun(result_array, intervals, gen_title(gen_name, dist_name))
            self.load_image('мой график.png', self.label_3, 560)
        elif self.radioButton_3.isChecked():
            gen_name = 'lemer'
            for i in range(elements):
                result_array[get_bin(get_rand(gen_name, dist_name, min=0, max=1), binscount=intervals)] += 1
            draw_fun(result_array, intervals, gen_title(gen_name, dist_name))
            self.load_image('мой график.png', self.label_3, 560)

#-------------------------------------------------------------------------------------------------------------------
    def click_triangular(self):
        dist_name = 'triangular'
        elements = int(self.lineEdit_3.text())
        intervals = int(self.lineEdit_4.text())
        result_array = [0 for i in range(intervals)]
        if self.radioButton_4.isChecked():
            dist_name = 'triangular'
        elif self.radioButton_5.isChecked():
            dist_name = 'trapezoidal'
        if self.radioButton_6.isChecked():
            gen_name = 'default'
            for i in range(elements):
                result_array[get_bin(get_rand(gen_name, dist_name, min=0, max=1), binscount=intervals)] += 1
            draw_fun(result_array, intervals, gen_title(gen_name, dist_name))
            self.load_image('мой график.png', self.label_4, 540)
        elif self.radioButton_7.isChecked():
            gen_name = 'simple'
            for i in range(elements):
                result_array[get_bin(get_rand(gen_name, dist_name, min=0, max=1), binscount=intervals)] += 1
            draw_fun(result_array, intervals, gen_title(gen_name, dist_name))
            self.load_image('мой график.png', self.label_4, 540)
        elif self.radioButton_8.isChecked():
            gen_name = 'lemer'
            for i in range(elements):
                result_array[get_bin(get_rand(gen_name, dist_name, min=0, max=1), binscount=intervals)] += 1
            draw_fun(result_array, intervals, gen_title(gen_name, dist_name))
            self.load_image('мой график.png', self.label_4, 540)

# -------------------------------------------------------------------------------------------------------------------

    def click_normal(self):
        dist_name = 'normal'
        elements = int(self.lineEdit_5.text())
        intervals = int(self.lineEdit_6.text())
        result_array = [0 for i in range(intervals)]
        if self.radioButton_12.isChecked():
            dist_name = 'normal1'
        elif self.radioButton_13.isChecked():
            dist_name = 'normal2'
        if self.radioButton_9.isChecked():
            gen_name = 'default'
            for i in range(elements):
                result_array[get_bin(get_rand(gen_name, dist_name, mean=10, deviation=1),min= 0, max=+13, binscount=intervals)] += 1
            draw_fun(result_array, intervals, gen_title(gen_name, dist_name), 0, 13,)
            self.load_image('мой график.png', self.label_8, 540)
        elif self.radioButton_10.isChecked():
            gen_name = 'simple'
            for i in range(elements):
                result_array[get_bin(get_rand(gen_name, dist_name, mean=10, deviation=1), min= 0, max=+13, binscount=intervals)] += 1
            draw_fun(result_array, intervals, gen_title(gen_name, dist_name), 0, 13,)
            self.load_image('мой график.png', self.label_8, 540)
        elif self.radioButton_11.isChecked():
            gen_name = 'lemer'
            for i in range(elements):
                result_array[get_bin(get_rand(gen_name, dist_name, mean=10, deviation=1), min= 0, max=+13, binscount=intervals)] += 1
            draw_fun(result_array, intervals, gen_title(gen_name, dist_name), 0, 13,)
            self.load_image('мой график.png', self.label_8, 540)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Сыпачёв А. ИДБ-17-07"))
        self.radioButton.setText(_translate("Dialog", "Встроенная функция генерации случайных чисел на интервале [0;1]"))
        self.radioButton_2.setText(_translate("Dialog", "Метод простых конгруэнций"))
        self.radioButton_3.setText(_translate("Dialog", "Метод линейной конгруэнтной последовательности Лемера Д.Г."))
        self.label.setText(_translate("Dialog", "Количество элементов"))
        self.label_2.setText(_translate("Dialog", "Количество интервалов"))
        self.pushButton.setText(_translate("Dialog", "Генерировать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Равномерное распределение"))
        self.radioButton_4.setText(_translate("Dialog", "Треугольное"))
        self.radioButton_5.setText(_translate("Dialog", "Трапецеидальное"))
        self.radioButton_6.setText(
            _translate("Dialog", "Встроенная функция генерации случайных чисел на интервале [0;1]"))
        self.radioButton_7.setText(_translate("Dialog", "Метод простых конгруэнций"))
        self.radioButton_8.setText(_translate("Dialog", "Метод линейной конгруэнтной последовательности Лемера Д.Г."))
        self.label_5.setText(_translate("Dialog", "Количество элементов"))
        self.label_6.setText(_translate("Dialog", "Количество интервалов"))
        self.pushButton_2.setText(_translate("Dialog", "Генерировать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Симпсона"))
        self.label_7.setText(_translate("Dialog", "Количество элементов"))
        self.radioButton_9.setText(_translate("Dialog", "Встроенная функция генерации случайных чисел"))
        self.radioButton_10.setText(_translate("Dialog", "Метод простых конгруэнций"))
        self.radioButton_11.setText(_translate("Dialog", "Метод линейной конгруэнтной последовательности Лемера Д.Г."))
        self.radioButton_12.setText(_translate("Dialog", "По методичке"))
        self.radioButton_13.setText(_translate("Dialog", "Не по методичке"))
        self.pushButton_3.setText(_translate("Dialog", "Генерировать"))
        self.label_9.setText(_translate("Dialog", "Количество интервалов"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Нормальное распределение"))
        self.label_10.setText(_translate("Dialog", "Количество элементов"))
        self.radioButton_14.setText(
            _translate("Dialog", "Встроенная функция генерации случайных чисел на интервале [0;1]"))
        self.radioButton_15.setText(_translate("Dialog", "Метод простых конгруэнций"))
        self.radioButton_16.setText(_translate("Dialog", "Метод линейной конгруэнтной последовательности Лемера Д.Г."))
        self.radioButton_17.setText(_translate("Dialog", "Экспоненциальное"))
        self.radioButton_18.setText(_translate("Dialog", "Гиперэкспоненциальное"))
        self.pushButton_4.setText(_translate("Dialog", "Генерировать"))
        self.label_12.setText(_translate("Dialog", "Количество интервалов"))
        self.label_13.setText(_translate("Dialog", "lambda 1"))
        self.label_14.setText(_translate("Dialog", "lambda 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Экспоненциальное"))
        self.label_35.setText(_translate("Dialog", "Количество элементов"))
        self.label_36.setText(_translate("Dialog", "Количество интервалов"))
        self.pushButton_9.setText(_translate("Dialog", "Генерировать"))
        self.radioButton_40.setText(
            _translate("Dialog", "Встроенная функция генерации случайных чисел на интервале [0;1]"))
        self.radioButton_41.setText(_translate("Dialog", "Метод простых конгруэнций"))
        self.radioButton_42.setText(_translate("Dialog", "Метод линейной конгруэнтной последовательности Лемера Д.Г."))
        self.label_38.setText(_translate("Dialog", "a"))
        self.label_39.setText(_translate("Dialog", "b"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "Эрланг"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
